# User Settings | Edit there as per required

title: Arul's Blog
url: "https://blog.arul.me"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    arul's blog

email: official@arul.me
author: Arul Kumaran
# This description will show up in google search results
# (for index page) etc.
description: >
    Blog posts, writeups and guides written by Arul

# This will what will show against &copy; in the footer
copyright: xxdydx 2016-2021
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
        Hello! I am Arul, a student from Singapore. I love eating, sleeping and tinkering with computers. I am also an amateur CTF player who is learning the ropes. Hit me up at 
        <a href = mailto:official@arul.me>official(at)arul(dot)me</a>
        for a chat or anything.
        
permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    A Singaporean student who's interested in computers and CTFs.
    
about_footer: true

github_username: arul00

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/logo.jpg
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-101044636-1
 # GA Tracking ID


####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
